@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Medmoriser *-right-> "1" UniqueQAndAList
Medmoriser *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueQAndAList
UniqueTagList -[hidden]down- UniqueQAndAList

UniqueTagList *-right-> "*" Tag
UniqueQAndAList o-right-> QAndA

QAndA -up-> "*" Tag

QAndA *--> Question
QAndA *--> Answer
@enduml
