@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MedmoriserParser" as MedmoriserParser MEDMORISER_PARSER_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser COMMAND_PARSER_COLOR
participant "d:DeleteCommand" as DeleteCommand COMMAND_COLOR
participant ":CommandResult" as CommandResult COMMAND_RESULT_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> MedmoriserParser : parseCommand("delete 1")
activate MedmoriserParser

create DeleteCommandParser
MedmoriserParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> MedmoriserParser
deactivate DeleteCommandParser

MedmoriserParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> MedmoriserParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> MedmoriserParser
destroy DeleteCommandParser

MedmoriserParser --> LogicManager : d
deactivate MedmoriserParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteQAndA(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml