@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMedmoriser <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Medmoriser
Class ReadOnlyMedmoriser
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package QAndA {
Class QAndA
Class Answer
Class Question
Class UniqueQAndAList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Medmoriser .up.|> ReadOnlyMedmoriser

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Medmoriser
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Medmoriser *--> "1" UniqueQAndAList
UniqueQAndAList o--> "*" QAndA
QAndA *--> Question
QAndA *--> Answer
QAndA *--> "*" Tag

ModelManager -->"1" QAndA : filtered list
@enduml
