@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface MedmoriserStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonMedmoriserStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> MedmoriserStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonMedmoriserStorage .left.|> MedmoriserStorage
JsonMedmoriserStorage .down.> JsonSerializableMedmoriserStorage
JsonSerializableMedmoriserStorage .right.> JsonAdaptedQAndA
JsonAdaptedQAndA .right.> JsonAdaptedTag
@enduml
