/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from lightest to darkest

!define UI_COLOR #F28080
!define UI_COLOR_T1 #D97373
!define UI_COLOR_T2 #BF6565
!define UI_COLOR_T3 #166800
!define UI_COLOR_T4 #0E4100

!define LOGIC_COLOR #A9EEE6
!define LOGIC_COLOR_T1 #8BC4BE
!define LOGIC_COLOR_T2 #6A6ADC
!define LOGIC_COLOR_T3 #1616B0
!define LOGIC_COLOR_T4 #101086

!define MODEL_COLOR #C4AEE6
!define MODEL_COLOR_T1 v
!define MODEL_COLOR_T2 #E41F36
!define MODEL_COLOR_T3 #7B000E
!define MODEL_COLOR_T4 #51000A

!define STORAGE_COLOR #B3BD84
!define STORAGE_COLOR_T1 #E4F0A8
!define STORAGE_COLOR_T2 #EDC520
!define STORAGE_COLOR_T3 #806600
!define STORAGE_COLOR_T2 #544400

!define MEDMORISER_PARSER_COLOR #EDC1C0
!define COMMAND_PARSER_COLOR #EDC891

!define COMMAND_COLOR #83A6DE

!define COMMAND_RESULT_COLOR #C78FAB

!define USER_COLOR #000000

skinparam BackgroundColor #FEFAEC

skinparam Shadowing false

skinparam Class {
    FontColor #000000
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #FFFFFF
    FontName Roboto Light
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Roboto Light
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #000000
    FontName Roboto Light
}

skinparam Participant {
    FontColor #000000
    FontName Roboto Light
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
